#!/bin/bash

function echo_red() {
        echo -e "\\033[31;1m${@}\033[0m"
}

function echo_green() {
        echo -e "\\033[32;1m${@}\033[0m"
}


if [ -z $1 ]
  then
	echo_red "Wrong parameter !!!"
	echo "Uasge: build <BUILD METHOD>"
	echo "cross     Cross-Compile"
	echo "dist      Dist-cc"
	echo "native    Compile native"
fi

case "$1" in
	cross)
	echo_green "Cross Compiling ..."
	#make -j8 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- TARGET=UNIX
	make TARGET=CUBIE
	;;
	
	dist)
	echo_green "Building with dist-cc ..."
	;;

	native)
	echo_green "Building on native system ..."
	make
	;;

	*)
	echo_red "Wrong parameter !!!"
	echo "Uasge: build <BUILD METHOD>"
	echo "cross 	Cross-Compile"
	echo "dist:	Dist-cc"
	echo "native: 	Compile native"
	;;
esac
